/*
 * This file is part of mission-control
 *
 * Copyright (C) 2008 Nokia Corporation. 
 *
 * Contact: Alberto Mardegan  <alberto.mardegan@nokia.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * version 2.1 as published by the Free Software Foundation.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA
 *
 */

#ifndef __MC_REMAP_H__
#define __MC_REMAP_H__


#define mc_account_create omc_account_create
#define mc_account_delete omc_account_delete
#define mc_account_free omc_account_free
#define mc_account_get_alias omc_account_get_alias
#define mc_account_get_avatar omc_account_get_avatar
#define mc_account_get_avatar_id omc_account_get_avatar_id
#define mc_account_get_display_name omc_account_get_display_name
#define mc_account_get_normalized_name omc_account_get_normalized_name
#define mc_account_get_param_boolean omc_account_get_param_boolean
#define mc_account_get_param_int omc_account_get_param_int
#define mc_account_get_param_string omc_account_get_param_string
#define mc_account_get_params omc_account_get_params
#define mc_account_get_profile omc_account_get_profile
#define mc_account_get_secondary_vcard_fields omc_account_get_secondary_vcard_fields
#define mc_account_get_supported_presences omc_account_get_supported_presences
#define mc_account_get_type omc_account_get_type
#define mc_account_get_unique_name omc_account_get_unique_name
#define mc_account_is_complete omc_account_is_complete
#define mc_account_is_enabled omc_account_is_enabled
#define mc_account_lookup omc_account_lookup
#define mc_account_lookup_with_profile omc_account_lookup_with_profile
#define mc_account_lookup_with_vcard_field omc_account_lookup_with_vcard_field
#define mc_account_manager_proxy_get_type omc_account_manager_proxy_get_type
#define mc_account_monitor_get_supported_presences omc_account_monitor_get_supported_presences
#define mc_account_monitor_get_type omc_account_monitor_get_type
#define mc_account_monitor_new omc_account_monitor_new
#define mc_account_proxy_get_type omc_account_proxy_get_type
#define mc_account_reset_avatar_id omc_account_reset_avatar_id
#define mc_account_set_alias omc_account_set_alias
#define mc_account_set_avatar omc_account_set_avatar
#define mc_account_set_avatar_from_data omc_account_set_avatar_from_data
#define mc_account_set_avatar_mime_type omc_account_set_avatar_mime_type
#define mc_account_set_avatar_token omc_account_set_avatar_token
#define mc_account_set_display_name omc_account_set_display_name
#define mc_account_set_enabled omc_account_set_enabled
#define mc_account_set_normalized_name omc_account_set_normalized_name
#define mc_account_set_param_boolean omc_account_set_param_boolean
#define mc_account_set_param_int omc_account_set_param_int
#define mc_account_set_param_string omc_account_set_param_string
#define mc_account_set_secondary_vcard_fields omc_account_set_secondary_vcard_fields
#define mc_account_supports_presence omc_account_supports_presence
#define mc_account_unset_param omc_account_unset_param
#define mc_accounts_filter omc_accounts_filter
#define mc_accounts_list omc_accounts_list
#define mc_accounts_list_by_enabled omc_accounts_list_by_enabled
#define mc_accounts_list_by_profile omc_accounts_list_by_profile
#define mc_accounts_list_by_secondary_vcard_field omc_accounts_list_by_secondary_vcard_field
#define mc_accounts_list_by_vcard_field omc_accounts_list_by_vcard_field
#define mc_accounts_list_free omc_accounts_list_free
#define mc_cli_account_call_remove omc_cli_account_call_remove
#define mc_cli_account_call_update_parameters omc_cli_account_call_update_parameters
#define mc_cli_account_connect_to_account_property_changed omc_cli_account_connect_to_account_property_changed
#define mc_cli_account_connect_to_removed omc_cli_account_connect_to_removed
#define mc_cli_account_do_remove omc_cli_account_do_remove
#define mc_cli_account_do_update_parameters omc_cli_account_do_update_parameters
#define mc_cli_account_interface_avatar_connect_to_avatar_changed omc_cli_account_interface_avatar_connect_to_avatar_changed
#define mc_cli_account_manager_call_create_account omc_cli_account_manager_call_create_account
#define mc_cli_account_manager_connect_to_account_removed omc_cli_account_manager_connect_to_account_removed
#define mc_cli_account_manager_connect_to_account_validity_changed omc_cli_account_manager_connect_to_account_validity_changed
#define mc_cli_account_manager_do_create_account omc_cli_account_manager_do_create_account
#define mc_cli_dbus_properties_do_get omc_cli_dbus_properties_do_get
#define mc_cli_dbus_properties_do_get_all omc_cli_dbus_properties_do_get_all
#define mc_cli_dbus_properties_do_set omc_cli_dbus_properties_do_set
#define mc_filter_flag_get_type omc_filter_flag_get_type
#define mc_filter_priority_get_type omc_filter_priority_get_type
#define mc_iface_quark_account omc_iface_quark_account
#define mc_iface_quark_account_interface_avatar omc_iface_quark_account_interface_avatar
#define mc_iface_quark_account_interface_compat omc_iface_quark_account_interface_compat
#define mc_iface_quark_account_interface_conditions omc_iface_quark_account_interface_conditions
#define mc_iface_quark_account_manager omc_iface_quark_account_manager
#define mc_iface_quark_account_manager_interface_query omc_iface_quark_account_manager_interface_query
#define mc_make_resident omc_make_resident
#define mc_manager_clear_cache omc_manager_clear_cache
#define mc_manager_free omc_manager_free
#define mc_manager_get_bus_name omc_manager_get_bus_name
#define mc_manager_get_filename omc_manager_get_filename
#define mc_manager_get_object_path omc_manager_get_object_path
#define mc_manager_get_type omc_manager_get_type
#define mc_manager_get_unique_name omc_manager_get_unique_name
#define mc_manager_lookup omc_manager_lookup
#define mc_managers_free_list omc_managers_free_list
#define mc_managers_list omc_managers_list
#define mc_presence_get_type omc_presence_get_type
#define mc_profile_clear_cache omc_profile_clear_cache
#define mc_profile_free omc_profile_free
#define mc_profile_get_avatar_mime_type omc_profile_get_avatar_mime_type
#define mc_profile_get_branding_icon_name omc_profile_get_branding_icon_name
#define mc_profile_get_capabilities omc_profile_get_capabilities
#define mc_profile_get_configuration_ui omc_profile_get_configuration_ui
#define mc_profile_get_default_account_domain omc_profile_get_default_account_domain
#define mc_profile_get_default_account_name omc_profile_get_default_account_name
#define mc_profile_get_default_setting omc_profile_get_default_setting
#define mc_profile_get_display_name omc_profile_get_display_name
#define mc_profile_get_icon_name omc_profile_get_icon_name
#define mc_profile_get_priority omc_profile_get_priority
#define mc_profile_get_protocol omc_profile_get_protocol
#define mc_profile_get_protocol_name omc_profile_get_protocol_name
#define mc_profile_get_supported_presences omc_profile_get_supported_presences
#define mc_profile_get_type omc_profile_get_type
#define mc_profile_get_unique_name omc_profile_get_unique_name
#define mc_profile_get_vcard_field omc_profile_get_vcard_field
#define mc_profile_get_vcard_mangle omc_profile_get_vcard_mangle
#define mc_profile_is_default_for_vcard_field omc_profile_is_default_for_vcard_field
#define mc_profile_lookup omc_profile_lookup
#define mc_profile_lookup_default_for_vcard_field omc_profile_lookup_default_for_vcard_field
#define mc_profile_supports_presence omc_profile_supports_presence
#define mc_profiles_free_list omc_profiles_free_list
#define mc_profiles_list omc_profiles_list
#define mc_profiles_list_by_protocol omc_profiles_list_by_protocol
#define mc_profiles_list_by_vcard_field omc_profiles_list_by_vcard_field
#define mc_protocol_free omc_protocol_free
#define mc_protocol_free_params_list omc_protocol_free_params_list
#define mc_protocol_get_manager omc_protocol_get_manager
#define mc_protocol_get_name omc_protocol_get_name
#define mc_protocol_get_params omc_protocol_get_params
#define mc_protocol_get_type omc_protocol_get_type
#define mc_protocol_lookup omc_protocol_lookup
#define mc_protocol_print omc_protocol_print
#define mc_protocols_free_list omc_protocols_free_list
#define mc_protocols_list omc_protocols_list
#define mc_protocols_list_by_manager omc_protocols_list_by_manager
#define mc_signals_marshal_VOID__STRING_STRING omc_signals_marshal_VOID__STRING_STRING
#define mc_status_get_type omc_status_get_type
#define mc_type_dbus_struct_uss omc_type_dbus_struct_uss

#endif

